---
title: "sms-cimat-r-projects - Example Report"
author: "IsaiasGutierrez"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: tango
    toc: true
    toc_float: true
    code_folding: hide
  pdf_document:
    toc: true
    number_sections: true
params:
  data_file: "Rendimiento.xlsx"
---

```{r setup, include=FALSE}
# Setup chunk
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 6,
  fig.align = "center",
  cache = FALSE
)

# Load required libraries
library(here)

library(tidyverse)
library(readxl)

library(plotly)

```

# Introduction


# Data Loading and Preprocessing

```{r data-loading}

# data_path <- here("data", "raw", params$data_file)
data_path <- here("data", "raw", "Rendimiento.xlsx")

rendimiento <- read_excel( data_path,col_types = c("numeric", "text","text", "text", "numeric", "numeric", "text", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))


plot(table(rendimiento$Marca))


```
